### ISSUE TITLE
Solve -O3 issues on vectorized variant

### ISSUE THREAD

**Issue by gut** [PPC64/sha2-le#2]
Currently (3f25bf22b30fedc85801e26b917de12b4737b52c) when compiling with ´-O3` the `sha256_hw` outputs wrong results for inputs bigger than a block and `sha512_hw` is raising segmentation faults.

The issue is due to the inline assembly found inside of `calc_compression` function.

**Comment by racardoso** [comment]
I would suggest to add `volatile` (I saw on Friday that `calc_compression` call a `__asm__` without `volatile`) on asm inline but seems that you already do that. I'll test it tomorrow.

**Comment by racardoso** [comment]
I notice two strange behaviors. I add a print function just before the loops  on sha2_ll_asm file and the code works (?). 

So inspect the asm code via gcc -Wa,-adhln -O3 it don't save the frame pointer between calls due a `fomit-frame-pointer` optimization and it lost the pointer. Calling a printf it forces to not apply  `fomit-frame-pointer` there. So i just add a `-fno-omit-frame-pointer` to Makefile. 

When call sha512 we got a segmentation fault, the code try access a invalid pointer. When call some C functions bellow. I solve it by add a `-fPIC` but this is more like a "luck guess" because i have a similar problem with asm inline before. 

It's hard to debug a code when it's optimized :/ 

Closed fc2789c7991443881cb67ad276cce346571e1fc8

**Comment by gut** [comment]
It didn't work for me on 92349bffbaae3b6836339644a5c177be0d5d6ac1:
```
Running tests for SHA-512:
_c is Ok
_intrinsics is NOK!
-6511f9f88f5c01c1d71f6b1d1952f855040ee22d26b982dde6e69559d2ef5afd21fa26533c4d95f6353858c15c1e03e8b9dd6178891d0ca6cdc7ab67a5e12285
+ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f
_asm is Ok
```

**Comment by racardoso** [comment]
@gut I already solved it here. I am just running perf here and I will push the fix for this problem. It was solved before but I made some changes on intrinsics after this fix that broke SHA512.

**Comment by racardoso** [comment]
Check cd1e5a9f67565ce143f27e6efda0d50d1132204f

**Comment by racardoso** [comment]
I'll close this as the test are passing now. The last problem seem to be a gcc bug. If we have any other problems with instrisics variant we may open another issue.
